services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: resumeiq_user
      POSTGRES_PASSWORD: resumeiq_pass
      POSTGRES_DB: resumeiq_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resumeiq_user -d resumeiq_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
